name: Create Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build usb zip
        run: |
          cd usb
          mkdir usb-${{ github.ref_name }}
          cp -r usb/* usb-${{ github.ref_name }}
          zip -r usb.zip usb-${{ github.ref_name }}
      - name: Build console executable
        run: |
          cd console
          make build
          cd dist
          mv console console-${{ github.ref_name }}
          zip console.zip console-${{ github.ref_name }}
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            usb/usb.zip
            console/dist/console.zip
